# Generated by Django 5.1.4 on 2024-12-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('senha', models.CharField(max_length=50)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('associacao', models.CharField(choices=[('a', 'ABD'), ('c', 'CAU'), ('r', 'CREA')], max_length=1)),
                ('resgistro', models.IntegerField(max_length=12, null=True)),
            ],
        ),
    ]
